<a href="https://colab.research.google.com/github/Mariam-Hamoda/Rock-vs-Mine-Prediction/blob/main/Rock_vs_Mine_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing the librires

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score

Data Processing

In [4]:
sonar_data=pd.read_csv("/content/Copy of sonar data.csv",header=None)

In [5]:
sonar_data.head()

       0       1       2       3       4   ...      56      57      58      59  60
0  0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1  0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2  0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3  0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4  0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R

[5 rows x 61 columns]

In [7]:
sonar_data.shape

(208, 61)

In [9]:
sonar_data[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [10]:
sonar_data.info

<bound method DataFrame.info of          0       1       2       3       4   ...      56      57      58      59  60
0    0.0200  0.0371  0.0428  0.0207  0.0954  ...  0.0180  0.0084  0.0090  0.0032   R
1    0.0453  0.0523  0.0843  0.0689  0.1183  ...  0.0140  0.0049  0.0052  0.0044   R
2    0.0262  0.0582  0.1099  0.1083  0.0974  ...  0.0316  0.0164  0.0095  0.0078   R
3    0.0100  0.0171  0.0623  0.0205  0.0205  ...  0.0050  0.0044  0.0040  0.0117   R
4    0.0762  0.0666  0.0481  0.0394  0.0590  ...  0.0072  0.0048  0.0107  0.0094   R
..      ...     ...     ...     ...     ...  ...     ...     ...     ...     ...  ..
203  0.0187  0.0346  0.0168  0.0177  0.0393  ...  0.0065  0.0115  0.0193  0.0157   M
204  0.0323  0.0101  0.0298  0.0564  0.0760  ...  0.0034  0.0032  0.0062  0.0067   M
205  0.0522  0.0437  0.0180  0.0292  0.0351  ...  0.0140  0.0138  0.0077  0.0031   M
206  0.0303  0.0353  0.0490  0.0608  0.0167  ...  0.0034  0.0079  0.0036  0.0048   M
207  0.0260  0.0363  0.0136  0.0272  0.0214  ...  0.0040  0.0036  0.0061  0.0115   M

[208 rows x 61 columns]>

In [11]:
sonar_data.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [15]:
#extract features and labels
coloum=sonar_data.shape[1]
print(coloum)

61

In [16]:
X=sonar_data.iloc[: , :coloum-1]
Y=sonar_data.iloc[: , coloum-1]
print(X)
print(Y)

         0       1       2       3   ...      56      57      58      59
0    0.0200  0.0371  0.0428  0.0207  ...  0.0180  0.0084  0.0090  0.0032
1    0.0453  0.0523  0.0843  0.0689  ...  0.0140  0.0049  0.0052  0.0044
2    0.0262  0.0582  0.1099  0.1083  ...  0.0316  0.0164  0.0095  0.0078
3    0.0100  0.0171  0.0623  0.0205  ...  0.0050  0.0044  0.0040  0.0117
4    0.0762  0.0666  0.0481  0.0394  ...  0.0072  0.0048  0.0107  0.0094
..      ...     ...     ...     ...  ...     ...     ...     ...     ...
203  0.0187  0.0346  0.0168  0.0177  ...  0.0065  0.0115  0.0193  0.0157
204  0.0323  0.0101  0.0298  0.0564  ...  0.0034  0.0032  0.0062  0.0067
205  0.0522  0.0437  0.0180  0.0292  ...  0.0140  0.0138  0.0077  0.0031
206  0.0303  0.0353  0.0490  0.0608  ...  0.0034  0.0079  0.0036  0.0048
207  0.0260  0.0363  0.0136  0.0272  ...  0.0040  0.0036  0.0061  0.0115

[208 rows x 60 columns]
0      R
1      R
2      R
3      R
4      R
      ..
203    M
204    M
205    M
206    M
207    M
Name: 60, Length: 208, dtype: object

In [40]:
#Transform 'R' and 'S' to number
dataEncode=LabelEncoder()

In [41]:
Y=dataEncode.fit_transform(Y)
#rock=1
#mine=0

In [20]:
print(Y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

Train and Test data

In [25]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2 ,random_state=42)

Train the model by Logistic Regression

In [22]:
model=LogisticRegression()

In [26]:
model.fit(X_train,Y_train)

LogisticRegression()

In [29]:
#accuracy the training data
train_prediction=model.predict(X_train)
training_data_accuracy=accuracy_score(train_prediction,Y_train)
print(training_data_accuracy)

0.8373493975903614

In [30]:
#accuracy the test data
test_prediction=model.predict(X_test)
test_data_accuracy=accuracy_score(test_prediction,Y_test)
print(test_data_accuracy)

0.7857142857142857

Making a Predictive System

In [31]:
input_data = (0.0203, 0.0121, 0.038, 0.0128, 0.0537, 0.0874, 0.1021, 0.0852, 0.1136, 0.1747, 0.2198, 0.2721, 0.2105, 0.1727, 0.204, 0.1786, 0.1318, 0.226, 0.2358, 0.3107, 0.3906, 0.3631, 0.4809, 0.6531, 0.7812, 0.8395, 0.918, 0.9769, 0.8937, 0.7022, 0.65, 0.5069, 0.3903, 0.3009, 0.1565, 0.0985, 0.22, 0.2243, 0.2736, 0.2152, 0.2438, 0.3154, 0.2112, 0.0991, 0.0594, 0.194, 0.1937, 0.1082, 0.0336, 0.0177, 0.0209, 0.0134, 0.0094, 0.0047, 0.0045, 0.0042, 0.0028, 0.0036, 0.0013, 0.0016)
input_data_array = np.asarray(input_data)
input_data_reshaped = input_data_array.reshape(1,-1)

In [42]:
model_prediction=model.predict(input_data_reshaped)
#original_label = dataEncode.inverse_transform(model_prediction)
#print(original_label)

In [44]:
if (model_prediction[0] == 0):
  print('The object is a Mine')
else:
  print('The object is a Rock')

The object is a Mine